# Generated by Django 2.1.7 on 2019-03-06 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=250)),
                ('drapeau', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=250)),
                ('present', models.BooleanField(max_length=250)),
                ('equipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Equipe')),
            ],
        ),
    ]
